export const IMAGES = {
  loginBg: require('../assets/images/bg/loginbg.png'),
  qrpopupBg: require('../assets/images/others/successcanbg.png'),
  splashBg: require('../assets/images/bg/splash_bg.png'),
  blockedBg: require('../assets/images/others/BlockedBg2.png'),
  requestmodalBg: require('../assets/images/others/requestmodalbg3.png'),
  unlockformBg: require('../assets/images/others/unlockformbackground.png'),
  dashboardBg: require('../assets/images/others/dashboardbg.png'),
  dashboardFirstOption: require('../assets/images/others/dashboardsecondoption.png'),
  dashboardSecondOption: require('../assets/images/others/dashboardfirstoption.png'),

  appText: require('../assets/images/icons/apptext.png'),
  signupText: require('../assets/images/others/signuptext.png'),
  blockedtitle: require('../assets/images/others/blockedtitle.png'),
  modaldesc: require('../assets/images/others/modaltext.png'),
  unlockText: require('../assets/images/others/unlockformtext.png'),
  unlockblurText: require('../assets/images/others/requestmodalblurtext.png'),
  requestTitle: require('../assets/images/others/requestitle.png'),
  requestblurTitle: require('../assets/images/others/requestmodalblurbuttontext.png'),

  questionIcon: require('../assets/images/icons/questionicon.png'),
  qrCodeIcon: require('../assets/images/others/qrcodeicon.png'),
  hideEye: require('../assets/images/icons/eye-hide.png'),
  showEye: require('../assets/images/icons/eye-show.png'),
  fbIcon: require('../assets/images/icons/fblogo.png'),
  twitterIcon: require('../assets/images/icons/twitter.png'),
  linkedinIcon: require('../assets/images/icons/linkedinlogo.png'),
  instaIcon: require('../assets/images/icons/instalogo2.png'),
  crossIcon: require('../assets/images/icons/orangecrossicon2.png'),
  tickIcon: require('../assets/images/others/tickicon.png'),
  countrycodeIcon: require('../assets/images/others/countrycode3.jpg'),
  tickcheckboxIcon: require('../assets/images/others/tick.png'),
  homeIcon: require('../assets/images/icons/home.png'),
  messageIcon: require('../assets/images/icons/message.png'),
  locationIcon: require('../assets/images/icons/location.png'),
  notificationIcon: require('../assets/images/icons/notification.png'),
  downloadIcon: require('../assets/images/icons/downloadicon.png'),
  backIcon: require('../assets/images/others/backicon2.png'),
  dropdownIcon: require('../assets/images/others/dropdownicon.png'),

  dummyDp: require('../assets/images/others/dummypic.png'),
};
